version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: gunicorn scrapy.wsgi:application --bind 0.0.0.0:8000
    entrypoint: ["/app/entrypoint.sh"]
